# Generated by Django 2.1.1 on 2018-10-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messdaten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offenname', models.CharField(blank=True, max_length=120, null=True)),
                ('O2', models.CharField(blank=True, max_length=120, null=True)),
                ('CO', models.CharField(blank=True, max_length=120, null=True)),
                ('CO2', models.CharField(blank=True, max_length=120, null=True)),
                ('NO', models.CharField(blank=True, max_length=120, null=True)),
                ('NO2', models.CharField(blank=True, max_length=120, null=True)),
                ('SO2', models.CharField(blank=True, max_length=120, null=True)),
                ('NOX', models.CharField(blank=True, max_length=120, null=True)),
                ('ETA', models.CharField(blank=True, max_length=120, null=True)),
                ('Lamda', models.CharField(blank=True, max_length=120, null=True)),
                ('Losses', models.CharField(blank=True, max_length=120, null=True)),
                ('Air_temperatur', models.CharField(blank=True, max_length=120, null=True)),
                ('Gas_temp', models.CharField(blank=True, max_length=120, null=True)),
                ('Airpressure', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
    ]
